api/urls.py
from django.conf.urls import patterns, include, url
from api import views

urlpatterns = [
    url(r'^locations/$', views.locations, name='locations'),
]

app/models.py
from __future__ import unicode_literals

from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
import calendar
import datetime



class H2OFlintDeliveryDate(models.Model):
    weekday = models.CharField(max_length=9, null=True, blank=True)
    month = models.CharField(max_length=9, null=True, blank=True)
    date = models.CharField(max_length=2, null=True, blank=True)
    year = models.CharField(max_length=4, default="2016")
    start_time = models.CharField(max_length=8)
    end_time = models.CharField(max_length=8)
    volunteers_needed = models.IntegerField(null=True, blank=True)
    volunteers_scheduled = models.IntegerField(null=True, blank=True)
    vehicles_needed = models.IntegerField(null=True, blank=True)
    vehicles_scheduled = models.IntegerField(null=True, blank=True)
    cases_to_deliver = models.IntegerField(null=True, blank=True)
    cases_delivered = models.IntegerField(null=True, blank=True)
    filters_to_deliver = models.IntegerField(null=True, blank=True)
    filters_delivered = models.IntegerField(null=True, blank=True)
    wipes_to_deliver = models.IntegerField(null=True, blank=True)
    wipes_delivered = models.IntegerField(null=True, blank=True)
    vaseline_to_deliver = models.IntegerField(null=True, blank=True)
    vaseline_delivered = models.IntegerField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(default = timezone.now)

    def __unicode__(self):
        return self.weekday+" "+self.month + " "+self.date+", "+self.start_time+"-"+self.end_time+" delivery run"


class DeliveryRequest(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    delivery_date = models.ForeignKey(H2OFlintDeliveryDate, null=True, blank=True)
    recipient_address = models.CharField(max_length=200, null=True, blank=True)
    longitude = models.FloatField(default = -83.6874562)
    latitude = models.FloatField(default = 43.0125274)
    recipient_phone = models.CharField(max_length=20, null=True, blank=True)
    zipcode = models.CharField(max_length=10, null=True, blank=True)
    persons_in_household = models.IntegerField(null=True, blank=True)
    cases_requested = models.IntegerField(null=True, blank=True)
    reason = models.TextField(null=True, blank=True)
    contact_first_name = models.CharField(max_length=45, null=True, blank=True)
    contact_last_name = models.CharField(max_length=45, null=True, blank=True)
    contact_phone = models.CharField(max_length=20, null=True, blank=True)
    video_url = models.CharField(max_length=200, null=True, blank=True)
    other_supplies_needed = models.TextField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    resolved = models.BooleanField(default = False)
    left_message = models.BooleanField(default = False)
    action_needed = models.BooleanField(default = False)
    no_contact = models.BooleanField(default = True)
    calltime_notes = models.TextField(default="", null=True, blank=True)
    date_created = models.DateTimeField(default = timezone.now)

    def __unicode__(self):
        return self.user.first_name+" "+self.user.last_name + ", "+self.recipient_address


class IndividualHelper(models.Model):
    user = models.ForeignKey(User)
    user_type = models.IntegerField(default = 1)
    local = models.BooleanField(default=False)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=20, null=True, blank=True)
    state = models.CharField(max_length=4, null=True, blank=True)
    zipcode = models.CharField(max_length=10, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)

    date_created = models.DateTimeField(default = timezone.now)

    def __unicode__(self):
        return self.user.first_name+" "+self.user.last_name


class IndividualHelpOffer(models.Model):
    individual_helper = models.ForeignKey(IndividualHelper, null=True, blank=True)
    wants_to_volunteer = models.BooleanField(default=False)
    group_size = models.IntegerField(null=True, blank=True)
    will_unload = models.BooleanField(default=False)
    will_deliver_with_vehicle = models.BooleanField(default=False)
    will_do_admin = models.BooleanField(default=False)
    will_do_testing = models.BooleanField(default=False)
    will_do_plumbing = models.BooleanField(default=False)
    other_help = models.TextField(null=True, blank=True)
    mon_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    mon_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    tue_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    tue_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    wed_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    wed_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    thu_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    thu_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    fri_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    fri_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    sat_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    sat_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    sun_availability_start_time = models.CharField(max_length=8, null=True, blank=True)
    sun_availability_end_time = models.CharField(max_length=8, null=True, blank=True)
    availability_start_date = models.CharField(max_length=2, null=True, blank=True)
    availability_end_date = models.CharField(max_length=2, null=True, blank=True)
    availability_start_month = models.CharField(max_length=9, null=True, blank=True)
    availability_end_month = models.CharField(max_length=9, null=True, blank=True)
    availability_start_year = models.CharField(max_length=4, null=True, blank=True)
    availability_end_year = models.CharField(max_length=4, null=True, blank=True)
    cases_count = models.IntegerField(null=True, blank=True)
    pallets_count = models.IntegerField(null=True, blank=True)
    back_braces_count = models.IntegerField(null=True, blank=True)
    dollies_count = models.IntegerField(null=True, blank=True)
    vaseline_count = models.IntegerField(null=True, blank=True)
    wipes_count = models.IntegerField(null=True, blank=True)
    dollar_donation_amount = models.FloatField(null=True, blank=True)
    total_amount = models.FloatField(null=True, blank=True)
    note_for_recipient = models.TextField(null=True, blank=True)
    doing_park_and_serve = models.BooleanField(default = False)
    park_and_serve_address = models.CharField(max_length=200, null=True, blank=True)
    park_and_serve_city = models.CharField(max_length=45, default = 'Flint')
    park_and_serve_state = models.CharField(max_length=4, default = 'MI')
    park_and_serve_zipcode = models.CharField(max_length=10, null=True, blank=True)
    park_and_serve_month = models.CharField(max_length=9, null=True, blank=True)
    park_and_serve_weekday = models.CharField(max_length=9, null=True, blank=True)
    park_and_serve_date = models.CharField(max_length=2, null=True, blank=True)
    park_and_serve_items = models.CharField(max_length=140, null=True, blank=True)
    park_and_serve_year = models.CharField(max_length=4, default="2016")
    park_and_serve_start_time = models.CharField(max_length=8, null=True, blank=True)
    park_and_serve_end_time = models.CharField(max_length=8, null=True, blank=True)
    video_url = models.CharField(max_length=200, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    resolved = models.BooleanField(default = False)
    left_message = models.BooleanField(default = False)
    action_needed = models.BooleanField(default = False)
    no_contact = models.BooleanField(default = True)
    calltime_notes = models.TextField(default="", null=True, blank=True)
    date_created = models.DateTimeField(default = timezone.now)


    def __unicode__(self):
        return unicode(self.individual_helper) +" "+unicode(self.date_created)


class Organization(models.Model):
    contact = models.ForeignKey(User)
    approved = models.BooleanField(default=False)
    org_name = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=45, default = "Flint")
    state = models.CharField(max_length=4, default = "MI")
    zipcode = models.CharField(max_length=10, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    website = models.CharField(max_length=200, null=True, blank=True)
    public_email = models.CharField(max_length=200, null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    has_water = models.BooleanField(default=False)
    has_volunteers = models.BooleanField(default=False)
    has_vehicles_or_drivers = models.BooleanField(default=False)
    has_testers = models.BooleanField(default=False)
    has_filters = models.BooleanField(default=False)
    has_testing_skills = models.BooleanField(default=False)
    has_plumbing_skills = models.BooleanField(default=False)
    has_wipes = models.BooleanField(default=False)
    has_vaseline = models.BooleanField(default=False)
    has_lifting_supplies = models.BooleanField(default=False)
    has_other_supplies = models.BooleanField(default=False)
    other_supplies_on_hand = models.TextField(null=True, blank=True)
    needs_water = models.BooleanField(default=False)

app/templates/about.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
{% load i18n %}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-md-10 col-md-offset-2">
            <h1 class="about-header blue-text">{% trans "About this site" %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-4 col-md-offset-2">
        <h3>{% trans "What is FlintH2O" %}</h3>
            <p><b>{% trans '"A first-world solution to a third-world situation."' %}</b>
            <br>{% trans "We are a Flint-based, community-led, media-centered start-up. The concept for this digital platform was made by “subterranean” community and grassroots leaders and Flint residents who have been physically serving people affected by the crisis for the last several months through various community-operated distribution hubs. Our aim is to leverage technology to change the human condition, to make sure all residents have access to receive the resources, information, and services they need, want, and deserve. Flint H2O was launched on February 24, 2016." %}</p>

            <p><b>{% trans '"An essential part of any sensible, sustainable, long-term plan for water distribution, crowd-sourced intelligence, and economic development."' %}</b>
            <br>{% trans "Months into the crisis, the City of Flint, Michigan continues in a state of emergency over water. To a significant segment of our population, there also continues to be a lack of coordination, communication, and centralization of pertinent Water Crisis information being readily, reliably, available to the people of Flint. We hope this digital online platform will help us all get and give the help that is needed." %}</p><br>

        <h3>{% trans "Who built this web app?" %}</h3>
            <p>{% trans "In response to the ongoing water crisis in the city, Darnell Ishmel, a Flint resident, has led the development of an innovative, web-based, digital online platform to effectively coordinate fresh water intake and distribution efforts. "%}</p>

            <p>{% trans "For their trustworthy vision, indomitable tenacity, boundless creativity and unwavering support, we offer special thanks to our team: " %}Dorian Jackson, Teresa Bingman, Maggie Ishmel, Quavon Kelly, Kasandra Wall, Jamale Ishmel, Brandon Townsel, Brandi Natale, Robert McCathern, Barbara Meadows, Samantha Parsons, and Aliya Rahman.</p><br>

            <p>{% trans "We'd also like to thank our beta testers for helping us build a strong website: " %} Lynn Nestor, Karl Kumodzi, Candace Johnson, Rodd Monts, Maggie Ishmel, Sharon Scott, Pam Magee, Kara Royal, Russell Kirksey, Mary Hammond, Jessica Tucker, Peter Heggs, Nicole Nelson, Komesia, Sherry Laurence, Neel W, Paul Mathis, Rebecca Eaddy, Tracy Ann Threat, Cheryl Ward, Sequina DuBose, Timothy Holley, Lynn Luelen, Joanne Baek, Melody Wilson, Michelle Wilson</p>


        <h3>{% trans "Who is this site for?" %}</h3>
            <p>{% trans "FlintH2o is for EVERYONE inside and outside of Flint, Michigan - including individuals, grassroots and Faith-Based organizations, non-profit organizations, and for profit businesses. Governmental entities and educational institutions are also invited to use this site. Most especially, this site was designed to serve those who Darnell Ishmel refers to as the City’s ‘subterranean populations’ – those of us who exist well below the grassroots. We, down here, need it the most. We are the ones most marginalized, most neglected, and most affected by this crisis. Technology should help make us all equal. It is 2016. There should be no digital divide." %}</p><br>

        <h3>{% trans "Who are our partners?" %}</h3>
            <p>{% trans "We may be dealing with this water situation for a long time to come. We are encouraged to know that there are companies in Flint and beyond, that have partnered with us so that we can help provide access to quality information, augment resource distribution, creating new job opportunities, and restore people to a quality of life they deserve." %}</p>
 
            <p><b>{% trans "FlintH2o" %}</b> {% trans "enjoys the partnership and support of: darnellishmelmedia, Elite Career Solutions, the Urban Renaissance Center, Voices for Flint, the Black Success Network, New World Flood, the C.H.A.N.G.E. Foundation, and Color of Change." %}</p><br>

        <h3>{% trans "Where can I learn more about the Flint water crisis?" %}</h3>
            <p>{% trans "Visit our" %} <a href="{% url 'faq' %}">{% trans "FAQ" %}</a> {% trans "page for answers to basic questions and links to more information." %}</p>
            <br><br>


        <h4>{% trans "View our" %} <a class="blue-text" href="{% url 'privacy' %}">{% trans "privacy policy" %}</a> {% trans "and" %} <a class="blue-text" href="{% url 'terms' %}">{% trans "terms and conditions of use" %}</a>.</h4>

        </div>




        <br><br><br>

        <div class="col-xs-12 col-md-4 col-md-offset-1">
            <div class="photo-wrapper">
                <img src="https://s3.amazonaws.com/h2oflint/get_involved_hoodie.JPG" rotate="90">
            </div>
            <div class="caption">
                <p>{% trans "<b>Want to get involved?</b> Ready to lend a hand? Please feel free to contact us if you think we may be able to facilitate your interest and commitment to empower people, resource communities, and help change the dominant narrative." %}
                </p>
            </div>
            <br>
            <div class="photo-wrapper">
                <img src="https://s3.amazonaws.com/h2oflint/members_of_flintH2O.JPG">
            </div>
            <div class="caption">
                <p>
                    {% trans "<b>Our gratitude:</b> Members of the FlintH2o thank you for visiting this page." %}
                </p>
            </div>
        </div>
    </div>
</div>



{% endblock %}

app/templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>{% trans "H2OFlint" %} - {% trans "Find or offer help through Flint community members" %}</title>
        <meta name="title" content="H2OFlint - Find or offer help through Flint community members"/>

        <!-- Bootstrap -->
        <!--<link href="{% static 'css/boostrap.min.css' %}" rel="stylesheet">-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="{% static 'js/application.js' %}"></script>

        <link href="{% static 'css/style.css' %}" rel="stylesheet">


        <!-- OpenGraph tags for social media sharing -->
        <meta property="og:title" content="H2OFlint - Find or offer help through Flint community members" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://www.h2oflint.com" />
        <meta property="og:site_name" content="H2OFlint" />
        <meta property="og:image" content="https://s3.amazonaws.com/h2oflint/opengraph_image.jpg" />

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- swf object -->
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>

        <script>
              (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
              })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

              ga('create', 'UA-74043800-1', 'auto');
              ga('send', 'pageview');

        </script>

    </head>

    <body>


        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
              
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                    <li><a class="navbar-brand logo" href="{% url 'index' %}"><img src="{% static 'img/logo_transparent.png' %}" {% trans "H2Oflint" %}</a></li>
                    <li><a class="navbar-brand" href="{% url 'about' %}">{% trans "About" %}</a></li>
                    <li><a class="navbar-brand" href="{% url 'faq' %}">{% trans "FAQ" %}</a></li>
                    <li><a class="navbar-brand" href="{% url 'data' %}">{% trans "Use our data/API" %}</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">

                {% if user.is_authenticated %}
                    {% if user.deliveryrequest_set.all|length > 0 %}
                        <li><a href="{% url 'edit_request_delivery' %}">{% trans "Edit My Profile" %}</a></li>
                    {% endif %}
                    {% if user.individualhelper_set.all|length > 0 %}
                        <li><a href="{% url 'edit_individual' %}">{% trans "Edit My Profile" %}</a></li>
                        <li><a href="{% url 'add_another_help_offer' %}">{% trans "Add Another Offer to Help" %}</a></li>
                    {% endif %}
                    {% if user.organization_set.all|length > 0 %}
                        <li><a href="{% url 'edit_organization' %}">{% trans "Edit My Organization's Profile" %}</a></li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li><a href="{% url 'staff_dashboard' %}">{% trans "Calltime Dashboard" %}</a></li>
                    {% endif %}
                <li><a href="{% url 'logout_view' %}">{% trans "Sign out" %}</a></li>
                {% else %}
                <li><a href="{% url 'request_delivery' %}">{% trans "I'm looking for help" %}</a></li>
                <li><a href="{% url 'individual_offer' %}">{% trans "I can help" %}</a></li>
                <li><a href="{% url 'organization_offer' %}">{% trans "My organization can help" %}</a></li>
                <li><a href="{% url 'register' %}">{% trans "Sign up" %}</a></li>
                <li><a href="{% url 'login_view' %}">{% trans "Log in" %}</a></li>
                {% endif %}
                </li>
                <li><a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.h2oflint.com&t=Find+Or+Offer+Help+In+Flint" target="_blank"><span class="share-buttons"><img src="{% static 'img/facebook.png' %}"></a></li>
                <li>
                <a href="http://twitter.com/share?url=http%3A%2F%2Fwww.h2oflint.com&text=H2O%20Flint%20lets%20folks%20find%20or%20share%20help%20through%20Flint%20community%20members&via=flint_h2o" target="_blank"><span class="share-buttons"><img src="{% static 'img/twitter.png' %}"></a></li>
                <li><a href="https://www.instagram.com/flint_h20/" target="_blank"><span class="share-buttons"><img src="{% static 'img/instagram.png' %}"></a></li>
                <li><a href="http://www.gofundme.com/h2oflint"><button class="btn btn-default blue-text"><b>{% trans "Donate" %}</b></button></a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        <div class="row sms-subheader dk-blue-bg ">
            <div class="col-xs-12 white-text">
                <b>{% trans 'Text "FlintH2O" to 24587 for info by SMS' %}</b>
            </div>
        </div>
        


        {% block content %}

        {% endblock %}

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <h3><b>{% trans 'Text "FlintH2o" to "24587"</b> to receive up-to-date distribution information by SMS or phone' %}</h3>
                                <h3>{% trans 'Got a live update from a water distribution site to add to this page? Tweet it to ' %}<a href="http://www.twitter.com/flint_h2o" class="white-text"><b><u>@flint_h2O</u></b></a></h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <h4 class="white-text">{% trans "For press inquiries, please email " %}<b>press@h2oflint.com</b></h4>
                                <h4 class="white-text">{% trans "For other non-emergency help, please email " %}<b>help@h2oflint.com</b></h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 white-text copyright">
                                <p><b><a class="white-text" href="{% url 'privacy' %}">{% trans "Privacy policy" %}</b></a> | <a class="white-text" href="{% url 'terms' %}"><b>{% trans "Terms and conditions of use" %}</b></a></p>
                                <p>{% trans "Copyright © 2016 H2OFlint. All Rights Reserved." %}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    </body>

</html>

app/templates/changes_updated.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
{% load i18n %}

<div class="container-fluid">
    <div class="row confirmation-body">
        <div class="col-xs-12 col-md-4 col-md-offset-2">
            <h3 class="blue-text"><b>{% trans "Your changes have been saved." %}</b></h3>
            <p><a href="{% url 'index' %}">{% trans "Click here" %}</a> {% trans "to return to the homepage." %}</p>
        </div>

            
        <div class="col-xs-12 col-md-4 col-md-offset-1">
            <div class="photo-wrapper">
                <img src="https://s3.amazonaws.com/h2oflint/one_volunteer_distributing_supplies_indoors_portrait.jpg">
            </div>
            <div class="caption">
                
            </div>
        </div>
    </div>
</div>



{% endblock %}

app/templates/privacy.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
{% load i18n %}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-md-10 col-md-offset-2">
            <br><h1 class="about-header blue-text">{% trans "Privacy policy" %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-4 col-md-offset-2">
    
            <p>{% trans "We collect personal information for various business purposes when you interact with us, such as registering you with our site, processing your order, responding to requests for service or assistance, creating and improving our website features and social media platforms, and protecting our rights and property. We collect information about you in two basic ways. First, we receive information directly from you. Second, through use of cookies and other technologies, we keep track of your interactions." %}</p>

            <p>{% trans "We do not sell, rent, or provide your personal information to third parties that are unaffiliated with Internet Brands. Your personal information is shared with third parties with your consent, except in circumstances where the law requires it to be shared. You may cancel your registration or deactivate your account, or update your preferences at any time." %}</p>




        </div>




        <br><br><br>

        <div class="col-xs-12 col-md-4 col-md-offset-1">
            <div class="photo-wrapper">
                <img src="https://s3.amazonaws.com/h2oflint/get_involved_hoodie.JPG" rotate="90">
            </div>
            <div class="caption">
                <p><b>{% trans "Want to get involved?" %}</b> {% trans "Ready to lend a hand? Please feel free to contact us if you think we may be able to facilitate your interest and commitment to empower people, resource communities, and help change the dominant narrative." %}
                </p>
            </div>
            <br>
            <div class="photo-wrapper">
                <img src="https://s3.amazonaws.com/h2oflint/members_of_flintH2O.JPG">
            </div>
            <div class="caption">
                <p>
                    {% trans "<b>Our gratitude:</b> Members of the FlintH2o thank you for visiting this page." %}
                </p>
            </div>
        </div>
    </div>
</div>



{% endblock %}

app/templates/request_received.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
{% load i18n %}

<div class="container-fluid">
    <div class="row confirmation-body">
        <div class="col-xs-12 col-md-4 col-md-offset-2">
            <h3 class="blue-text"><b>{% trans "We've received your information. Please check your email for a confirmation." %}</b></h3>
            <p><a href="{% url 'index' %}">{% trans "Click here" %}</a> {% trans "to return to the homepage." %}</p>
        </div>

            
        <div class="col-xs-12 col-md-4 col-md-offset-1">
            <div class="photo-wrapper">
                <img src="https://s3.amazonaws.com/h2oflint/one_volunteer_distributing_supplies_indoors_portrait.jpg">
            </div>
            <div class="caption">
                
            </div>
        </div>
    </div>
</div>



{% endblock %}